# -*- coding: utf-8 -*-
"""LAB3_1650700238_manopakorn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mCC_XpBahyqd_jxTH978Q67gtZw1KiXR
"""

#scriptpi01

#Table
print("="*43)
print("|%8s %s %7s |"%("***","Area Calculator Program","***"))
print("-"*43)
print("%s%22s%20s"%("|", "Shape code list :", "|"))
print("%s%22s%20s"%("|", "(R) Rectangle", "|"))
print("%s%22s%20s"%("|", "(T) Trapezoid", "|"))
print("%s%26s%16s"%("|", "(P) Parallelogram", "|"))
print("%s%19s%23s"%("|", "(C) Circle", "|"))
print("-"*43)



#Select code from [R,T,P,C]
code = input("    Select Code [R,T,P,C]: ")



#Code = R
if code == "R":
  print("%30s"%("You selected R = Rectangle"))
  print()

  #Compute Retangle_area
  print("="*40)
  print("%28s"%("Area of Rectangle"))
  print("="*40)
  print("Inputs width and height in cm. or m.")

  #Select unit
  unit = input("Select a unit code 1 (cm.) or 2 (m.): ")
  if unit == "1" or unit == "2":
    if unit == "1":
      unit = "cm2"
    elif unit == "2":
      unit = "m2"

    #Compute&Display area
    width = int(input("Enter width  : "))
    height = int(input("Enter height : "))
    if width <= 0 or height <= 0:
      if width <= 0 and height > 0:
        if width == 0 and height > 0:
          print("Invalid width (width cannot be zero)")
        elif width < 0 and height > 0:
          print("Invalid width (width cannot be negative integer)")  

      elif height <= 0 and width > 0:
        if height == 0 and width > 0:
          print("Invalid height (height cannot be zero)")
        elif height < 0 and width > 0:
          print("Invalid height (height cannot be negative integer)") 

      elif width <= 0 and height <= 0:
        if width == 0 and height == 0:
          print("Invalid width and height (width and height cannot be zero)")
        elif width < 0 and height < 0:
          print("Invalid width and height (width and height cannot be negative integer)")
        elif width == 0 and height < 0:
          print("Invalid width  (width cannot be zero)")
          print("Invalid height (height cannot be negative integer)") 
        elif width < 0 and height == 0:
          print("Invalid height (height cannot be zero)")
          print("Invalid width  (width cannot be negative integer)") 
    else:
      rectangle_area = width * height
      print("="*40)
      print("%18s%.2f %s"%("Area = ", rectangle_area, unit))
      print("="*40)
    
  else:
    print("Invalid unit")



#Code = T
elif code == "T":
  print("%30s"%("You selected T = Trapezoid"))
  print()
  
  #Compute Trapezoid_area 
  print("="*40)
  print("%29s"%("Area of Trapezoid"))
  print("="*40)
  print("Inputs parallel sides and height in cm. or m.")

  #Select unit
  unit = input("Select a unit code 1 (cm.) or 2 (m.): ")
  if unit == "1" or unit == "2":
    if unit == "1":
      unit = "cm2"
    elif unit == "2":
      unit = "m2"

    #Compute&Display area
    side_a = int(input("Enter parallel side(a) : "))
    side_b = int(input("Enter parallel side(b) : "))
    height = int(input("Enter height : "))
    if side_a <= 0 or side_b <= 0 or height <= 0:
      if side_a <= 0 and side_b <= 0 and height > 0:
        if side_a == 0 and side_b == 0 and height > 0:
          print("Invalid side_a and side_b (side_a and side_b cannot be zero)")
        elif side_a < 0 and side_b < 0 and height > 0:
          print("Invalid side_a and side_b (side_a and side_b cannot be negative integer)")   
        elif side_a < 0 and side_b == 0 and height > 0:
          print("Invalid side_a (side_a cannot be negative integer)")
          print("Invalid side_b (side_b cannot be zero)")
        elif side_a == 0 and side_b < 0 and height > 0:
          print("Invalid side_a (side_a cannot be zero)")
          print("Invalid side_b (side_b cannot be negative integer)")

      elif side_a <= 0 and side_b > 0 and height <= 0:
        if side_a == 0 and side_b > 0 and height == 0:
          print("Invalid side_a and height (side_a and height cannot be zero)")
        elif side_a < 0 and side_b > 0 and height < 0:
          print("Invalid side_a and height (side_a and height cannot be negative integer)")   
        elif side_a < 0 and side_b > 0 and height == 0:
          print("Invalid side_a (side_a cannot be negative integer)")
          print("Invalid height (height cannot be zero)")
        elif side_a == 0 and side_b > 0 and height < 0:
          print("Invalid side_a (side_a cannot be zero)")
          print("Invalid height (height cannot be negative integer)")

      elif side_a > 0 and side_b <= 0 and height <= 0:
        if side_a > 0 and side_b == 0 and height == 0:
          print("Invalid side_b and height (side_a and height cannot be zero)")
        elif side_a > 0 and side_b < 0 and height < 0:
          print("Invalid side_b and height (side_a and height cannot be negative integer)")   
        elif side_a > 0 and side_b > 0 and height == 0:
          print("Invalid side_b (side_a cannot be negative integer)")
          print("Invalid height (height cannot be zero)")
        elif side_a > 0 and side_b == 0 and height < 0:
          print("Invalid side_b (side_a cannot be zero)")
          print("Invalid height (height cannot be negative integer)")

      elif side_a > 0 and side_b > 0 and height <= 0:
        if side_a > 0 and side_b > 0 and height == 0:
          print("Invalid height (height cannot be zero)")
        elif side_a > 0 and side_b > 0 and height < 0:
          print("Invalid height (height cannot be negative integer)")  
        
      elif side_a <= 0 and side_b > 0 and height > 0:
        if side_a == 0 and side_b > 0 and height > 0:
          print("Invalid side_a (side_a cannot be zero)")
        elif side_a < 0 and side_b > 0 and height > 0:
          print("Invalid side_b (side_a cannot be negative integer)") 

      elif side_a > 0 and side_b <= 0 and height > 0:
        if side_a > 0 and side_b == 0 and height > 0:
          print("Invalid side_b (side_b cannot be zero)")
        elif side_a > 0 and side_b < 0 and height > 0:
          print("Invalid side_b (side_b cannot be negative integer)") 

      elif side_a <= 0 and side_b <= 0 and height <= 0:
        if side_a == 0 and side_b == 0 and height == 0:
          print("Invalid side_a, side_b and height (side_a, side_b and height cannot be zero)")
        elif side_a < 0 and side_b < 0 and height < 0:
          print("Invalid side_a, side_b and height (side_a, side_b and height cannot be negative integer)")
        elif side_a < 0 and side_b < 0 and height == 0:
          print("Invalid side_a, side_b (side_a and side_b cannot be negative integer)")
          print("Invalid height (height cannot be zero)")
        elif side_a < 0 and side_b == 0 and height < 0:
          print("Invalid side_a and height (side_a and height cannot be negative integer)")
          print("Invalid side_b (side_b cannot be zero)")
        elif side_a == 0 and side_b < 0 and height < 0:
          print("Invalid side_b and height (side_b and height cannot be negative integer)")
          print("Invalid side_a (side_a cannot be zero)")
        elif side_a == 0 and side_b == 0 and height < 0:
          print("Invalid side_a and side_b (side_a and side_b cannot be zero)")
          print("Invalid height (height cannot be negative integer)")
        elif side_a < 0 and side_b == 0 and height == 0:
          print("Invalid side_b and height (side_b and height cannot be zero)")
          print("Invalid side_a (side_a cannot be negative integer)")
        elif side_a == 0 and side_b < 0 and height == 0:
          print("Invalid side_a and height (side_a and height cannot be zero)")
          print("Invalid side_b (side_b cannot be negative integer)")
          
    else:
      trapezoid_area = 0.5*(side_a + side_b)*height
      print("="*40)
      print("%18s%.2f %s"%("Area = ", trapezoid_area, unit))
      print("="*40) 

  else:
    print("Invalid unit")



#Code = P
elif code == "P":
  print("%34s"%("You selected P = Parallelogram")) 
  print()
  
  #Parallelpgram_area
  print("="*40)
  print("%32s"%("Area of Parallelpgram"))
  print("="*40)
  print("Inputs base and height in cm. or m.")

  #Select unit
  unit = input("Select a unit code 1 (cm.) or 2 (m.): ")
  if unit == "1" or unit == "2":
    if unit == "1":
      unit = "cm2"
    elif unit == "2":
      unit = "m2"
    
    #Compute&Display area
    base = int(input("Enter base   : "))
    height = int(input("Enter height : "))
    if base <= 0 or height <= 0:
      if base <= 0 and height > 0:
        if base == 0 and height > 0:
          print("Invalid base (base cannot be zero)")
        elif base < 0 and height > 0:
          print("Invalid base (base cannot be negative integer)")  

      elif height <= 0 and base > 0:
        if height == 0 and base > 0:
          print("Invalid height (height cannot be zero)")
        elif height < 0 and base > 0:
          print("Invalid height (height cannot be negative integer)") 

      elif base <= 0 and height <= 0:
        if base == 0 and height == 0:
          print("Invalid base and height (base and height cannot be zero)")
        elif base < 0 and height < 0:
          print("Invalid base and height (base and height cannot be negative integer)")
        elif base == 0 and height < 0:
          print("Invalid base   (base cannot be zero)")
          print("Invalid height (height cannot be negative integer)") 
        elif base < 0 and height == 0:
          print("Invalid height (height cannot be zero)")
          print("Invalid base   (base cannot be negative integer)")  
    else:
      #Compute Parallelpgram_area
      parallelpgram_area = base*height
      print("="*40)
      print("%18s%.2f %s"%("Area = ", parallelpgram_area, unit))
      print("="*40)
    
  else:
    print("Invalid unit")



#Code = C
elif code == "C":
  print("%27s"%("You selected C = Circle")) 
  print()
  
  #Circle_area
  print("="*40)
  print("%25s"%("Area of Circle"))
  print("="*40)
  print("Inputs radius in cm. or m.")

  #Select unit
  unit = input("Select a unit code 1 (cm.) or 2 (m.): ")
  if unit == "1" or unit == "2":
    if unit == "1":
      unit = "cm2"
    elif unit == "2":
      unit = "m2"

    #Compute&Display area
    radius = int(input("Enter radius: "))
    if radius <= 0:
      if radius < 0:
        print("Invalid radius (radius cannot be negative integer)")
      elif radius == 0:
        print("Invalid radius (radius cannot be zero)")

    else:
      #Compute Circle_area
      circle_area = 22/7*radius**2
      print("="*40)
      print("%18s%.2f %s"%("Area = ", circle_area, unit))
      print("="*40)
    
  else:
    print("Invalid unit !!")



#Error
else:
  print("%16s %s %20s"%("You selected", code, "is Invalid shape code!"))
  print("%21s"%("Please try again."))